In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d.flatten()


array([1, 2, 3, 4, 5, 6])

In [3]:
arr2d.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [5]:
arr = np.array([10, 20, 30, 40, 50, 60])
np.split(arr, 3)


[array([10, 20]), array([30, 40]), array([50, 60])]

In [6]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

r=np.vsplit(arr, 3)
r=np.hsplit(arr, 3)
r

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [7]:
from numpy import random
x=random.randint(100)
print(x)


12


In [8]:
x=random.rand()
x


0.1285207497781119

In [9]:
x=random.rand(10)
x

array([0.62912739, 0.66841387, 0.54623568, 0.68508007, 0.24521964,
       0.57668706, 0.57670747, 0.87033027, 0.84226706, 0.29154756])

In [10]:
x=random.randint(100,size=(5))
x


array([25, 24,  3, 11, 45], dtype=int32)

In [11]:
x=random.randint(100,size=(3,5))
print(x)

[[44 55 38 58 43]
 [ 0 51 20 74 56]
 [32 17 60 86 11]]


In [12]:
x=random.choice([3,5,7,9])
print(x)

5


In [13]:
import random
for i in range(2):
    print(random.randint(1,1000))
for i in range (2):
    random.seed(0)
    print(random.randint(1,1000))

767
977
865
865


In [14]:
import random
for i in range(5):
    print(random.randint(1,10))
for i in range (5):
    random.seed(0)
    print(random.randint(1,10))

7
7
1
5
9
7
7
7
7
7


In [15]:
range_arr=np.arange(1,21)
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
zeros_arr = np.zeros((3, 4)) 
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
range_arr=np.arange(1,13)
range_arr.resize(3,4)
range_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr=np.array([10,20,30,40,50])
arr[3]

np.int64(40)

In [19]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[2:7]

array([3, 4, 5, 6, 7])

In [20]:
range_arr=np.arange(2,51,2)
range_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [21]:
import numpy as np
arr=[20,2,7,1,34]
print(np.mean(arr))

12.8


In [22]:
import numpy as np
arr=[20,2,7,1,34]
print(np.median(arr))

7.0


In [23]:
a=[1,7,3,9,5]
b=[6,2,8,4,10]
num=np.maximum(a,b)
print(num)

[ 6  7  8  9 10]


In [24]:
a=([1,2],[3,4])
b=([5,6],[7,8])
num=np.multiply(a,b)
num

array([[ 5, 12],
       [21, 32]])

In [25]:
arr=np.unique([1,2,2,3,4,4,5])
arr

array([1, 2, 3, 4, 5])